version: '3'
services:
  mysql:
    build: docker/mysql
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ROOT_HOST: '%'
    restart: always
  app:
    build: docker/java
    environment:
        MYSQL_IP: mysql
        MYSQL_PORT: 3306
        MYSQL_PASSWORD: root
        MYSQL_USERNAME: root
    ports: 
        - 18080:18080
