server:
  port: 18080
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_IP}:${MYSQL_PORT}/sakila?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
#spring:
#  datasource:
#    url: jdbc:mysql://39.108.59.99/sakila?serverTimezone=UTC&characterEncoding=utf8&useUnicode=true&useSSL=false
#    username: root
#    password: root
 #配置pageHelper分页插件的内容
pagehelper:
  helper-dialect: mysql
  params: countSql
  support-methods-arguments: true
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#logging:
#  level:
#    com.tk: error